apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: core-app-vs
  namespace: istio-system
spec:
  exportTo:
  - "*"
  hosts:
  - "app.rezz.io"
  gateways:
  - argocd-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: core-app-svc.default.svc.cluster.local
        subset: core-app-subset
      weight: 100
