apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-cert-conf
  namespace: default
data:
  root.pem: |-
    -----BEGIN CERTIFICATE-----
    MIID6TCCAtGgAwIBAgIIJ7RTQgvZyX4wDQYJKoZIhvcNAQELBQAwXTELMAkGA1UE
    BhMCUlUxCzAJBgNVBAgMAk1PMQ8wDQYDVQQHDAZNb3Njb3cxETAPBgNVBAoMCHJl
    enouZGV2MQswCQYDVQQLDAJJVDEQMA4GA1UEAwwHcmV6ei1jYTAeFw0yNDAyMDMw
    NzQxMDRaFw0yNTAyMDIwNzQxMDRaMF0xCzAJBgNVBAYTAlJVMQswCQYDVQQIDAJN
    TzEPMA0GA1UEBwwGTW9zY293MREwDwYDVQQKDAhyZXp6LmRldjELMAkGA1UECwwC
    SVQxEDAOBgNVBAMMB3JlenotY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQCcmrOsopaeq6mVleX0DamBvpGV0yCWlRw1AsSOQdmvuTUsLN6dYALtwxEG
    UFfo02vtV0Ao1lAmhnqfQJinjxQ4fK5ufj2X+9UNsPhg14ff2rLHIdUfaI3NIhfU
    T7560MEyIunYcwVYbJcswwe/9obBlW2KAV1YhrOU0z7B/yt+fRfKe780xEdgklUK
    pnPOd4igAxHhQoizCFvRNjh0RncBm16+4YYaarKNYFPsF3KQXvr9By/udvKb+ygP
    4PgOYlLUAaAYBGzT/r8pifw7wFYOkXOpKxQnGT/JKYQl3zzm2PD+DoL9Cqp2dEPV
    axe+exLKhPBg+BDOeeiHmmcf2AiXAgMBAAGjgawwgakwDwYDVR0TAQH/BAUwAwEB
    /zAOBgNVHQ8BAf8EBAMCAbYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
    MB0GA1UdDgQWBBS1u+i+LgCdGuSBhI1AAs88088ivTAiBgNVHR8EGzAZMBegFaAT
    hhFodHRwOi8vL2NybC8xLmNybDAkBglghkgBhvhCAQ0EFxYVR2VuZXJhdGVkIGJ5
    IFJvdXRlck9TMA0GCSqGSIb3DQEBCwUAA4IBAQA0jkFEoPhiqBFGRV+W3bQ4ldGu
    Gia7kwpiOiNgQfc5KBdQ0TmZL7yQSC7norHUzxcq54YrOT5IjE//V8aqyiJBz4/T
    ZiAKxDltcPQTvl1+W120quF+q1AIEKnjsV1bIbi91zgkxWhtuqQ+op+MTzW3Lte3
    Ca3t0FE1Rmwc7VvWUX6LUMtpjopPsG+QaOII1uyP3S5ee84puctIx3VmptN1kvT2
    ggIGlT1Xj+daWBUj+dgQHIaN1+yGu9CXYvHrLtesEBuW1VnHTBW9k6b2c4SI65bw
    6W66ae6fYPjsLmzTq78S0hJ7jvL0B+TMN7ut06CzRVd3E+E9X2GwJNyzbDT8
    -----END CERTIFICATE-----
  filebeat.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIEEDCCAvigAwIBAgIIY7izc+gzcjUwDQYJKoZIhvcNAQELBQAwXTELMAkGA1UE
    BhMCUlUxCzAJBgNVBAgMAk1PMQ8wDQYDVQQHDAZNb3Njb3cxETAPBgNVBAoMCHJl
    enouZGV2MQswCQYDVQQLDAJJVDEQMA4GA1UEAwwHcmV6ei1jYTAeFw0yNDAyMDQx
    MzM2NDhaFw0yNTAyMDMxMzM2NDhaMGUxCzAJBgNVBAYTAlJVMQswCQYDVQQIDAJN
    TzEPMA0GA1UEBwwGTW9zY293MREwDwYDVQQKDAhyZXp6LmRldjELMAkGA1UECwwC
    SVQxGDAWBgNVBAMMD2VsYXN0aWMucmV6ei5pbzCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAKiFuXTxecqJPCINiuFmkSI5EBBFd9kifqN9H1+KFhAJCx0I
    Iwy4LDul+zOEsMBVNEsuoy7GpjQfM2lDck2dKFXDkoazZ5a152YpXH/Ww6u55Ukv
    lKbXSKN2NXNXQozjVda7DqsnH15uAPxPkg3uvfnvpJPHMqprdBRXschPSyPmUsqx
    WnTdeFXS+Vwp7hKfP3LKx6+S4Noc0qZR1Q4Fjz3j1p1vnJeCIBp3cgufjDT3R3+8
    1kQgmSIknOyAky+8s6G1+K8lM8iWM8jxSSRTkVUr9hQQbqK6NTmBfR9DkSPkHBrY
    E9a8Soo9ceg9ns3KNbGOl18BQ9iI6f6IJYhkVFsCAwEAAaOByzCByDAPBgNVHRMB
    Af8EBTADAQH/MA4GA1UdDwEB/wQEAwIBtjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
    KwYBBQUHAwIwHQYDVR0OBBYEFB8PE2yTncIod/3EyyrMDpF3GhRzMB8GA1UdIwQY
    MBaAFLW76L4uAJ0a5IGEjUACzzzTzyK9MCAGA1UdEQQZMBeCD2VsYXN0aWMucmV6
    ei5pb4cEwKhYZTAkBglghkgBhvhCAQ0EFxYVR2VuZXJhdGVkIGJ5IFJvdXRlck9T
    MA0GCSqGSIb3DQEBCwUAA4IBAQBIeFlD4Wsp4EZrUFHApkriUGIKn/+0PSgnJe7B
    WI2B8Mq3+L0p0h3D1MVxaqdRHB/e/yA5UYkCxei4/kmBLLVMM7So4gm1pCmY64Ia
    4Z+phc4NEtFRC0K9PUrjaL0vwr/Tr80dCMYZm2VX7UYSFF+Os+T7jdQnDfzWWkmh
    tY5Z4UN3KcIoOpFsBClGjiULPgVlS1pdbxlDsTcIvQdpA/quM3hxh9ojaq/Aiwis
    gwVjjUhWOiPaenVG0xfgjJmJ8kaIvxotLDP9/MfRy1ZuKISHjinaHW5vI20KJWav
    xOUt8l9/t5KrknlJpdloGJJFyJkJtxtP6iaHDU+s4/DRx+GS
    -----END CERTIFICATE-----
  filebeat.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCohbl08XnKiTwi
    DYrhZpEiORAQRXfZIn6jfR9fihYQCQsdCCMMuCw7pfszhLDAVTRLLqMuxqY0HzNp
    Q3JNnShVw5KGs2eWtedmKVx/1sOrueVJL5Sm10ijdjVzV0KM41XWuw6rJx9ebgD8
    T5IN7r3576STxzKqa3QUV7HIT0sj5lLKsVp03XhV0vlcKe4Snz9yysevkuDaHNKm
    UdUOBY8949adb5yXgiAad3ILn4w090d/vNZEIJkiJJzsgJMvvLOhtfivJTPIljPI
    8UkkU5FVK/YUEG6iujU5gX0fQ5Ej5Bwa2BPWvEqKPXHoPZ7NyjWxjpdfAUPYiOn+
    iCWIZFRbAgMBAAECggEAf7V/WtkYY91mPaQnqDLzL40w2DPc5CcY80qB+QQLPjGs
    Q18EOMJlevqJCHy4+bhYPdVlArC2CW/PpSjguWKsy3m/U+cnTHYjmy8jExotBLmG
    wdSWAW3KdV3Cmdr56wzo4ya0sg2e3w/cHVkrpPVU8NCj1v2xLqbpu/TNHLDCj7vj
    9vhvMhex9/JNlIeXsuIs5ZVWHvg1u3MRY/x62/FdWmgTAjhJq4F6eS6k18a8+31q
    EPbwCg7lCtsaXWXG0sIOBqH/HrqvV/8FagTmHafsx9VGVrHjgCzyBOPvPs9eWerB
    BVmUdzAOQoEkiNEc1VnPg67UqMUvHKWzQ/1GzPaHmQKBgQDVyboN5aTZThgINHBk
    oQ0d5jgxGABi5kUBRk8YPQ6aETk5uI1Bkuu4ylhARNwLDhgm+LwWN7vY+n2+a2OP
    dQP1MPZCn95Dc+8SCRN/sJ/sNSQebBtuH5/HIlhUUr3dz5kudTAVh0N5AXGcHTaL
    JKKdYKFS9E03MjuE0qTySTOBFQKBgQDJy/hdfUixV0iwY6kqN18iGhWCg3poCYTV
    +PzXcUJfSCH9YVwLXF0DWQCktHZLw+Bu9kN4cQ6Lrtlxvwi3AatX3eVjDr9IBsQV
    LrksboAndCG6Q9wlVKSjOWm0KdTnfd+wQt3QF0ZGpc3LLMkEm2zBC3JyyK5+UXxE
    Dh4FCQJ7rwKBgC3EZ8490VKsAz0ObNk+GR7DgFgSOVLy1Ob29EvOFmgpM8UFm0fk
    eg4vU0E+/JRpSgZdzXY8LDzBM1Ymi0PU2yoMd0vACccK9K05wDDf0PyyS68vmZez
    sXLiCWLT682mebaWY9rYADvRcU7oehrDlwR2AVNO9ZDRcih3J9SukxYZAoGAGPGq
    mLvU0X8NkCgxj/NaQhfhUsm3xsZuchieAG+Smb6L3Qs82nanVLOavcFE4iarRmwQ
    eQHYn3GUlVfc1upQ6MKYCT+Ya2nSsR+eahyaoMXdKW4b901YMIj3RPrqw1au4NXT
    H1bRLAhwwM2fZ39i2RX2JrQhxaGC79Ki6VJsyScCgYBPJ8wbqlZ6FFzDw6jdzzPY
    YAqMCCyA8zWLSMN7stIinpqCTG955tVBPhIkk21bHbZdkNJTcN4HM9Dcn4VIQKjv
    G3SjgqR1JJLeyzDDMVvby8Rg7/3BZGLuFd5rBfgSu67mZJBYHbu0Q+KVsdTVQLf6
    V/7C6gNcx652q5jk01IRsQ==
    -----END PRIVATE KEY-----
