---
- name: SETUP WEB SERVER
  hosts: web
  vars:
   rpm:
   - httpd
   - firewalld
   svc:
   - httpd
   - firewalld
  rule: http
  tasks:
  - name: INSTALL PACKAGES
     yum:
     name: "{{ rpm }}"
     state: latest
  - name: SETUP SERVICE
   service:
     name: "{{ item }}"
     state: started
     enabled: yes
     loop: "{{ svc }}"
  - name: ALLOW HTTP ACCESS
   firewalld:
     service: "{{ rule }}"
     state: enabled
     immediate: yes
     permanent: yes

