#!/bin/bash

set -x
# Экспорт переменных
export CLUSTER_ENDPOINT="https://127.0.0.1:6443"
export CLUSTER_NAME="rezz-cluster"
export USER_NAME="cluster-admin"


openssl genrsa -out $USER_NAME.key 2048
openssl req -new -key $USER_NAME.key -out $USER_NAME.csr -subj "/CN=$USER_NAME/O=$USER_NAME-group"


BASE64_CSR=$(cat $USER_NAME.csr | base64 | tr -d '\n')
echo $BASE64_CSR


# CSR для кластера
sleep 2
cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: $USER_NAME-csr
spec:
  request: $BASE64_CSR  # Вставьте сюда полученную строку
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400  # Срок действия: 24 часа
  usages:
  - client auth
EOF


sleep 2
kubectl get csr $USER_NAME-csr
kubectl certificate approve $USER_NAME-csr

sleep 1
kubectl get csr $USER_NAME-csr -o jsonpath='{.status.certificate}' | base64 -d | openssl x509 -text -noout
kubectl get csr $USER_NAME-csr -o jsonpath='{.status.certificate}' | base64 -d > $USER_NAME.crt


cat /etc/kubernetes/pki/ca.crt > cluster-ca.crt


sleep 1
# Создаем новый конфиг
kubectl config set-cluster $CLUSTER_NAME \
  --certificate-authority=cluster-ca.crt \
  --embed-certs=true \
  --server=$CLUSTER_ENDPOINT \
  --kubeconfig=$USER_NAME.kubeconfig

sleep 1
# Добавляем креды
kubectl config set-credentials $USER_NAME \
  --client-certificate=$USER_NAME.crt \
  --client-key=$USER_NAME.key \
  --embed-certs=true \
  --kubeconfig=$USER_NAME.kubeconfig

sleep 1
# Создаем контекст
kubectl config set-context $USER_NAME@$CLUSTER_NAME \
  --cluster=$CLUSTER_NAME \
  --user=$USER_NAME \
  --kubeconfig=$USER_NAME.kubeconfig



# тут провека пермишенов

kubectl config use-context $USER_NAME@$CLUSTER_NAME --kubeconfig=$USER_NAME.kubeconfig


kubectl auth whoami --kubeconfig=$USER_NAME.kubeconfig

kubectl auth can-i get pods -A --kubeconfig=$USER_NAME.kubeconfig

kubectl auth can-i delete pods -A --kubeconfig=$USER_NAME.kubeconfig


set +x
echo "DONE! $USER_NAME.kubeconfig"
