apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: 250Mi
    defaultRequest: # this section defines default requests
      cpu: 300m
      memory: 200Mi
    max: # max and min define the limit range
      cpu: "1"
    min:
      cpu: 100m
    type: Container