apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: default-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway-rezz
    app: ingressgateway-rezz
  servers:
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    hosts:
    - "app1.rezz.io"
    tls:
      mode: SIMPLE
      caCertificates: /root/root.pem
      serverCertificate: /root/rezz.pem
      privateKey: /root/rezz.key
