apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress-egress-iop
  namespace: rezz-dev
spec:
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  profile: minimal 
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: rezz-dev
      enabled: true
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
    egressGateways:
    - name: istio-egressgateway
      namespace: rezz-dev
      enabled: true
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: egressgateway
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
      istio-egressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
