pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: '33acb6e6-e62f-4958-bba3-d64026ae3f31', keyFileVariable: 'KEY')]) {
                    sh '''
                    eval $(ssh-agent -s)
                    ssh-add "$KEY"
                    ssh -o StrictHostKeyChecking=no -i $KEY root@192.168.88.113 "hostname"
                    hostname
                    '''
                }
                sh id
            }
        }
        stage('The End') {
            steps {
                sh 'hostname'
            }
        }
    }
}
