pipeline { 
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('The End') {
            steps {
                echo 'exit'
            }
        }
    }
}