apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: ingressgateway-rezz-service-account
  labels:
    app: ingressgateway-rezz
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.20.2
    release: istio


