apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: core-app-vs
  namespace: default
spec:
  exportTo:
  - "."
  hosts:
  - "*"
  gateways:
  - istio-ingress-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: core-app-svc.default.svc.cluster.local
        subset: core-app-subset
      weight: 100