apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: core-app
  labels:
    app: core-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-app

  template:
    metadata:
      labels:
        app: core-app

    spec:
      containers:
      - name: core-app
        image: deleany/core-app:v2.5
        ports:
        - containerPort: 1111
        volumeMounts:
          - name: core-app-config
            mountPath: /app

        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi

        env:
        - name: __POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: __POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

        - name: __PORT_NAME
          valueFrom:
            configMapKeyRef:
              name: core-app-config
              key: port

      volumeMounts:
        - name: core-app-config
          mountPath: "/app"
          readOnly: true

    volumes:
      - name: core-app-config
        configMap:
          name: core-app-config
          items:
          - key: "config.ini"
            path: "config.ini"
          - key: "game-special-key"
            path: "game-special-key"