apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
 name: istio-egressgateway
 namespace: istio-system
spec:
 selector:
   istio: egressgateway
 servers:
 - port:
     number: 443
     name: http
     protocol: HTTP
   hosts:
   - "elastic.rezz.io"
 - port:
     number: 1531
     name: tcp
     protocol: TCP
   hosts:
   - "elastic.rezz.io"