apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-host-elk-se
spec:
  location: MESH_EXTERNAL
  hosts:
  - "elastic.rezz.io"
  ports:
  - name: tcp-elk
    number: 9200
    protocol: TCP
  resolution: DNS
