apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gateway-elk-vs
  namespace: default
spec:
  hosts:
  - "https://elastic.rezz.io/"
  exportTo:
  - "*"
  gateways:
  - mesh
  - istio-egressgateway
  http:
  - match:
    - port: 80
      gateways:
      - mesh
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
  - match:
    - port: 80
      gateways:
      - istio-egressgateway
    route:
    - destination:
        host: "https://elastic.rezz.io/"
        port:
          number: 9200
