apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gateway-elk-vs
  namespace: istio-system
spec:
  exportTo:
    - "*"
  hosts:
  - "elastic.rezz.io"
  gateways:
  - mesh
  - istio-egressgateway
  tls:
  - match:
    - port: 443
      gateways:
      - mesh
    route:
    - destination:
        host: istio-egressgateway
      weight: 100
  - match:
    - port: 443
      gateways:
      - istio-egressgateway
    route:
    - destination:
        host: "elastic.rezz.io"
      weight: 100
