apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: argocd-gw
  namespace: default
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-80
      protocol: HTTP
    hosts:
    - "argocd.rezz.io"
#    tls:
#      mode: SIMPLE
#      caCertificates: /root/root.pem
#      serverCertificate: /root/rezz.pem
#      privateKey: /root/rezz.key