apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: argocd-dst-rule
spec:
  host: argocd-server
  trafficPolicy:
    tls:
      mode: SIMPLE
      credentialName: tls-secret-rezz