apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ printf "%s-%s" .Chart.Name "gw"}}
  namespace: {{ .Values.namespace }}
  selector:
    istio: egressgateway
  servers:
  {{- with .Values.hosts }}
  - hosts:
    {{- toYaml . | nindent 4 }} 
  {{- end}}
  port:
    number: {{ .Values.port }}
    name: {{ printf "%s-%s" "tcp" ( toString .Values.port) }}
    protocol: TCP
