apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Chart.Name }}-gw
  namespace: {{ .Values.namespace }}
  selector:
    istio: egressgateway
  servers:
  {{- with .Values.hosts }}
  - hosts:
    {{- toYaml . | nindent 4 }} 
  {{- end}}
  port:
    number: {{ .Values.port }}
    name: tcp-{{ .Values.port}}
    protocol: TCP
