apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Chart.Name "external-svc"}}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: egressgateway
  ports:
  - name: {{ printf "%s-%s" "tcp" ( toString .Values.port) }}
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
