apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s-%s" .Chart.Name "vs" }}
  namespace: {{ .Values.namespace }}
spec:
  exportTo:
    - "."
  hosts:
  {{- range $host := .Values.hosts }}
  - {{ $host | quote }}
  {{- end }}
  gateways:
  - mesh
  - {{ printf "%s-%s" .Chart.Name "gw" }}
  tcp:
  - match:
    - port: {{ .Values.port }}
      gateways:
      - mesh
    route:
    - destination:
        host: {{ .Chart.Name }}-external-svc.{{ .Values.namespace }}.svc.cluster.local
      weight: 100
  - match:
    - port: {{ .Values.port }}
      gateways:
      - {{ .Chart.Name }}-gw
    route:
    - destination:
    # тут нужно подумать, как сделать лучше
        host:
        {{- range $host := .Values.hosts }}
        - {{ $host  | quote }}
      {{- end }}
        port:
          number: {{ .Values.port }}
      weight: 100
