apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ printf "%s-%s" .Chart.Name "se"}}
  namespace: {{ .Values.namespace }}
spec:
  exportTo:
    - "."
  location: MESH_EXTERNAL
  {{- with .Values.hosts }}
  hosts:
    {{- toYaml . | nindent 2 }}  
  {{- end}}
  {{- with .Values.ports }}
  ports:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  resolution: DNS
