apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ .Chart.Name }}-se
  namespace: {{ .Values.namespace }}
spec:
  exportTo:
    - "."
  location: MESH_EXTERNAL
  hosts:
  - "postgres.rezz.io"
  ports:
  - name: tcp-postgres
    number: {{ .Values.port }}
    protocol: TCP
  resolution: DNS
