apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}-vs
  namespace: {{ .Values.namespace }}
spec:
  exportTo:
    - "."
  hosts:
  -  {{ .Values.host | quote }}
  gateways:
  - mesh
  - {{ .Chart.Name }}-gw
  tcp:
  - match:
    - port: {{ .Values.port}}
      gateways:
      - mesh
    route:
    - destination:
        host: {{ .Chart.Name }}-external-svc.{{ .Values.namespace }}.svc.cluster.local
      weight: 100
  - match:
    - port: {{ .Values.port }}
      gateways:
      - {{ .Chart.Name }}-gw
    route:
    - destination:
        host: {{ .Values.host }}
        port:
          number: {{ .Values.port }}
      weight: 100
