apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-external-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: egressgateway
  ports:
  - name: tcp-{{ .Values.port }}
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
